// app/layout.tsx
import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap", // Optional for better performance
  variable: "--font-mont", // Set as a CSS variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-mont bg-[var(--color-light)]`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
